### ISSUE TITLE
Export fit pc, F, and Lc

### ISSUE THREAD

**Issue by MVRapp** [nicolagalvanetto/Fodis#1]
Hi Nicola,

I have recently downloaded Fodis for single molecule afm analysis (non-Matlab version). Is there a way to export the variable fit Pc, Lc, and F for each curve?

Thanks!

**Comment by galvanetto** [comment]
Hi,
At the moment in _TOOLS>>Export peaks info_ it is possible to export Lc (contour length) and F (maximum force of the peaks) in a .txt file.
This is done with **fixed persistence length** (the one set in parameter box).

Would you find helpful to export these peaks info with **free persistence length**?

**Comment by MVRapp** [comment]
Hello,

Yes, I would find it very useful to export the peak info (Lc and F) with
free persistence length. Thanks for any help that you can provide--the
software is very useful!

-Mike

**Comment by galvanetto** [comment]
Yes
I updated the code and the Windows version with this feature: 
_Tools >> Export peaks info - free persistence length._

I think you just need to download and launch the new **fodis.exe**.

Spread the word (and don't forget to credit Fodis on your research :)

Best
Nicola
