### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Deba5** [nicolagalvanetto/Fodis#2]
Respected Sir/Madam
 I am trying to fit the WLC model in a force-distance curve (. txt format) but the fitting is not completed. please guide me on how do I fit the model. If possible please tell me a step-by-step protocol. 
Regards 
Debashish

**Comment by galvanetto** [comment]
Hello:
if the data are in the proper format (see the user guide) you will use File>Import traces  (plain or rows depending on your format).
The traces will be loaded and you will see them in the screen.
Then you select the Trace-Lc plot and you have the fit with the wlc.
