### ISSUE TITLE
Manual deflection sensitivity input

### ISSUE THREAD

**Issue by Deba5** [nicolagalvanetto/Fodis#3]
Hi, 
How can I put a manual deflection sensitivity value in a particular force curve? I have tried to change the sensitivity value using the "pre-processing shift" option but no change in the result. when I import the trace the deflection sensitivity was 36nm/V but in FODIS it shows 12.88nm/V. 
Please Help

**Comment by galvanetto** [comment]
In pre processing you have to check/uncheck the option to change and write the value, you see immediately the scale that changes in the plot. Then you have to press apply to the the dataset: these are changes that are applied to all the traces. Then export again to have the file with the corrected traces
